/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdaptersRouteImport } from './routes/adapters'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SourceRouteImport } from './routes/source'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as WorldRouteImport } from './routes/world'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptersRoute = AdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/config': typeof ConfigRoute
  '/discovery': typeof DiscoveryRoute
  '/events': typeof EventsRoute
  '/knowledge': typeof KnowledgeRoute
  '/roadmap': typeof RoadmapRoute
  '/source': typeof SourceRoute
  '/systems': typeof SystemsRoute
  '/world': typeof WorldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/config': typeof ConfigRoute
  '/discovery': typeof DiscoveryRoute
  '/events': typeof EventsRoute
  '/knowledge': typeof KnowledgeRoute
  '/roadmap': typeof RoadmapRoute
  '/source': typeof SourceRoute
  '/systems': typeof SystemsRoute
  '/world': typeof WorldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/config': typeof ConfigRoute
  '/discovery': typeof DiscoveryRoute
  '/events': typeof EventsRoute
  '/knowledge': typeof KnowledgeRoute
  '/roadmap': typeof RoadmapRoute
  '/source': typeof SourceRoute
  '/systems': typeof SystemsRoute
  '/world': typeof WorldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adapters'
    | '/config'
    | '/discovery'
    | '/events'
    | '/knowledge'
    | '/roadmap'
    | '/source'
    | '/systems'
    | '/world'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adapters'
    | '/config'
    | '/discovery'
    | '/events'
    | '/knowledge'
    | '/roadmap'
    | '/source'
    | '/systems'
    | '/world'
  id:
    | '__root__'
    | '/'
    | '/adapters'
    | '/config'
    | '/discovery'
    | '/events'
    | '/knowledge'
    | '/roadmap'
    | '/source'
    | '/systems'
    | '/world'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptersRoute: typeof AdaptersRoute
  ConfigRoute: typeof ConfigRoute
  DiscoveryRoute: typeof DiscoveryRoute
  EventsRoute: typeof EventsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  RoadmapRoute: typeof RoadmapRoute
  SourceRoute: typeof SourceRoute
  SystemsRoute: typeof SystemsRoute
  WorldRoute: typeof WorldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapters': {
      id: '/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptersRoute: AdaptersRoute,
  ConfigRoute: ConfigRoute,
  DiscoveryRoute: DiscoveryRoute,
  EventsRoute: EventsRoute,
  KnowledgeRoute: KnowledgeRoute,
  RoadmapRoute: RoadmapRoute,
  SourceRoute: SourceRoute,
  SystemsRoute: SystemsRoute,
  WorldRoute: WorldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
